talav_user:
  resources:
    user:
      classes:
        model: Groshy\Entity\User
    user_oauth:
      classes:
        model: Groshy\Entity\UserOAuth
  email:
    from:
      email: samsung.android1890i@gmail.com
      name: Samsung Android
  registration:
    form:
      type: Groshy\Form\Type\RegistrationFormType
      model: Groshy\Form\Model\RegistrationFormModel

auto_mapper_plus:
  options:
    create_unregistered_mappings: true

#oneup_flysystem:
#  adapters:
#    default:
#      local:
#        location: "%kernel.project_dir%/public/media"
#  filesystems:
#    default:
#      adapter: default